"""initial schema

Revision ID: c1d400194cca
Revises: 
Create Date: 2026-07-01 19:56:12.602049
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = 'c1d400194cca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_audit_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_consumer'), 'alerts', ['consumer'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp_started', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_model_allowed', sa.Boolean(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_confidence', sa.Float(), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('complexity_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required_capabilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('logical_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('demo_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backend_fallback_used', sa.Boolean(), nullable=False),
    sa.Column('baseline_logical_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('baseline_logical_cost', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('estimated_savings', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('estimated_savings_ratio', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('max_tokens_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_output_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_output_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_logical_cost', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('actual_logical_cost', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('routing_overhead_cost', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('backend_cost', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('budget_charge', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('estimated_budget_charge', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('budget_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('post_stream_budget_overrun', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_consumer'), 'audit_records', ['consumer'], unique=False)
    op.create_index(op.f('ix_audit_records_status'), 'audit_records', ['status'], unique=False)
    op.create_table('budgets',
    sa.Column('consumer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('consumer')
    )
    op.create_table('recommendations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_consumer'), 'recommendations', ['consumer'], unique=False)
    op.create_index(op.f('ix_recommendations_type'), 'recommendations', ['type'], unique=False)
    op.create_table('usage_hourly',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logical_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
    sa.Column('actual_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_output_tokens', sa.Integer(), nullable=False),
    sa.Column('actual_output_tokens', sa.Integer(), nullable=False),
    sa.Column('logical_cost', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('routing_overhead_cost', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('backend_cost', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('estimated_savings', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('degraded_requests', sa.Integer(), nullable=False),
    sa.Column('blocked_requests', sa.Integer(), nullable=False),
    sa.Column('avg_latency', sa.Float(), nullable=True),
    sa.Column('p95_latency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_hourly_bucket_start'), 'usage_hourly', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_usage_hourly_consumer'), 'usage_hourly', ['consumer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_hourly_consumer'), table_name='usage_hourly')
    op.drop_index(op.f('ix_usage_hourly_bucket_start'), table_name='usage_hourly')
    op.drop_table('usage_hourly')
    op.drop_index(op.f('ix_recommendations_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_consumer'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_audit_records_status'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_consumer'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_consumer'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
